[build]
  command = "python manage.py migrate && python manage.py collectstatic --noinput"
  publish = "static"

[build.environment]
  DJANGO_SETTINGS_MODULE = "travel_booking.settings"
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
