# Generated by Django 5.2 on 2025-04-14 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("SL", "Sleeper"),
                            ("3A", "AC 3 Tier"),
                            ("2A", "AC 2 Tier"),
                            ("1A", "AC First Class"),
                            ("CC", "Chair Car"),
                            ("EC", "Executive Chair Car"),
                            ("GN", "General"),
                        ],
                        max_length=5,
                    ),
                ),
                ("fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_seats", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Train Classes",
            },
        ),
        migrations.CreateModel(
            name="TrainOperator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="train_operators"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("booking_reference", models.CharField(max_length=20, unique=True)),
                ("travel_date", models.DateField()),
                (
                    "seat_numbers",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("passenger_count", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "train_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="train.trainclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "train_type",
                    models.CharField(
                        choices=[
                            ("express", "Express"),
                            ("passenger", "Passenger"),
                            ("superfast", "Superfast"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trains",
                        to="train.trainoperator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("id_proof", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="train.trainbooking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=10,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(help_text="Expected journey duration"),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="train.station",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="train.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="train.train",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainclass",
            name="train_route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="train.trainroute",
            ),
        ),
        migrations.AddField(
            model_name="trainbooking",
            name="train_route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="train.trainroute",
            ),
        ),
    ]
